### ISSUE TITLE
Just a question - do you plan to work on this project further?

### ISSUE THREAD

**Issue by vijaygill** [srihari-humbarwadi/tensorflow_fcos#1]
Hi,

Do you plan to work on this project in future to complete the "To-do" tasks?

I am asking because I have found your code to be quite clean and easy to understand. I am slowly picking stuff here and there on computer vision and your code for Keras based retinanet got my attention and ever since I have been looking for more stuff from you.

Thanks
Vijay

**Comment by srihari-humbarwadi** [comment]
Hello, FCOS shares most of its components with RetinaNet, hence I am planning to include FCOS head in my https://github.com/srihari-humbarwadi/retinanet-tensorflow2.x repository. I will probably add it in a couple of months

**Comment by vijaygill** [comment]
> Hello, FCOS shares most of its components with RetinaNet, hence I am planning to include FCOS head in my https://github.com/srihari-humbarwadi/retinanet-tensorflow2.x repository. I will probably add it in a couple of months

That's fantastic! I am trying to get my head around that project too.

Thanks for for the good work.

I will close this ticket now as it was just a question and not an issue.
